# Generated by Django 4.1.6 on 2023-05-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='flatowner',
            name='name',
        ),
    ]
