# Generated by Django 4.1.6 on 2023-05-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0003_remove_flatowner_contact_flatowner_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatowner',
            name='gender',
        ),
    ]
