# Generated by Django 4.1.6 on 2023-05-30 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0004_remove_flatowner_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatowner',
            name='image',
            field=models.FileField(null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='AddFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('flat_type', models.CharField(max_length=30)),
                ('image', models.FileField(null=True, upload_to='media')),
                ('desc', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddFlat.flatowner')),
            ],
        ),
    ]
