# Generated by Django 4.1.6 on 2023-05-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0005_alter_flatowner_image_addflat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addflat',
            name='flat_type',
        ),
    ]
