# Generated by Django 4.1.6 on 2023-05-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0007_alter_addflat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addflat',
            name='flat_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
