# Generated by Django 4.1.6 on 2023-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0008_addflat_flat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatowner',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
