# Generated by Django 4.1.6 on 2023-06-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0011_addflat_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='image',
        ),
    ]
