# Generated by Django 4.1.6 on 2023-06-03 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0012_remove_usermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatowner',
            name='image',
        ),
    ]
