# Generated by Django 4.1.6 on 2023-06-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0013_remove_flatowner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
