# Generated by Django 4.1.6 on 2023-06-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0014_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
