# Generated by Django 4.1.6 on 2023-06-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0015_rename_contactus_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='addflat',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
