# Generated by Django 4.1.6 on 2023-06-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0017_remove_addflat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='addflat',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
