# Generated by Django 4.1.6 on 2023-06-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0018_addflat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addflat',
            name='status',
            field=models.CharField(default='Show Flat', max_length=50, null=True),
        ),
    ]
