# Generated by Django 4.1.6 on 2023-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0019_alter_addflat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addflat',
            name='status',
        ),
        migrations.AddField(
            model_name='addflat',
            name='flatstatus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
