# Generated by Django 4.1.3 on 2023-06-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddFlat', '0020_remove_addflat_status_addflat_flatstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addflat',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
    ]
